version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12-browsers
    steps:
      - add_ssh_keys
      - checkout
      - run: sudo apt-get install -y ffmpeg
      - run: yarn
      - run: mkdir -p output
      - run: node render --url=file://$PWD/examples/gsap-hello-world.html --video=output/gsap-hello-world.mp4 --parallelism=8
      - run: node render --url=file://$PWD/examples/gsap-hello-world.html --scale=0.1 --no-video --start=64 --end=65 --png=output/previews/gsap-hello-world
      - store_artifacts:
          path: output
          destination: output
