version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12-browsers
    steps:
      - add_ssh_keys
      - checkout
      - run: sudo apt-get install -y ffmpeg
      - run: yarn
      - run: mkdir -p output
      - run: node render.js --url=file://$PWD/examples/gsap-hello-world.html --video=output/gsap-hello-world.mp4
      - store_artifacts:
          path: output
          destination: output
