version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12-browsers
    steps:
      - add_ssh_keys
      - checkout
      - run: sudo apt-get install -y ffmpeg
      - run: yarn
      - run: mkdir -p output

      - run:
          command: node render --url=file://$PWD/examples/gsap-hello-world.html?render --video=output/gsap-hello-world.mp4 --parallelism=8
          when: always
      - run:
          command: node render --url=file://$PWD/examples/gsap-hello-world.html?render --scale=0.1 --no-video --start=64 --end=65 --png=output/previews/gsap-hello-world
          when: always

      - run:
          command: node render --url=file://$PWD/examples/vue-starfield.html?render --video=output/vue-starfield.mp4 --parallelism=4
          when: always
      - run:
          command: node render --url=file://$PWD/examples/vue-starfield.html?render --scale=0.1 --no-video --start=64 --end=65 --png=output/previews/vue-starfield
          when: always

      - store_artifacts:
          path: output
          destination: output
